### PR TITLE
Provide DeviceSingleRawReadStream to fetch just the latest reading.

### PR DESCRIPTION
**Pull request by apiology**
Happy to make any changes you'd suggest here--I'm relatively new to node, so if I'm doing something silly, just let me know.

Thanks!

### CODE REVIEW

**Comment by jed** [comment]
@apiology can you explain a bit more about what you're doing here?

**Comment by apiology** [comment]
Sure--basically, the goal was to pull just the latest reading from the API, rather than set up a continuous stream.  I use the new code in my package here--the README shows my motivation: https://github.com/apiology/freezerwatch

Despite the fact that I was only pulling one item, I didn't mind doing an asynchronous call, as I did want to be able to pull data from multiple sensors without waiting for the first response to make the next request, so I extended your already-working streaming code to drop the parameter which pulls a full week, and to drop the timeout to make the next request call.  I tried to share as much code as I could between the two modes--the common code is in DeviceStream.js.  I had both DeviceSingleRawReadStream and DeviceRawReadStream extend DeviceStream to make that happen.

You can see my use of this here: https://github.com/apiology/freezerwatch/blob/master/freezerwatch.js#L112

Thanks for taking a look at this!

**Comment by jed** [comment]
@apiology, i've added you as a collaborator, and would like to add you as an author on npm so that you can publish too... can you tell me what your user name is there?

**Comment by apiology** [comment]
Thanks!  I'm apiology on npm as well.

Any concerns on the PR, or should I go ahead and merge it?

**Comment by jed** [comment]
go ahead and merge at your discretion, and publish the new version to npm.

**Comment by apiology** [comment]
Version 0.2.0 has been published.

Thanks! 👍

**Pull request merged**
